import { z } from 'zod';
import { Competition } from '../models/Competition.js';
import { Registration } from '../models/Registration.js';
import { Participant } from '../models/Participant.js';
import { Submission } from '../models/Submission.js';
import { Referral } from '../models/Referral.js';
import { User } from '../models/User.js';
import { Review } from '../models/Review.js';
import { config } from '../config.js';
const participantInput = z.object({ name: z.string().trim().min(2).max(80), email: z.string().trim().email(), phone: z.string().trim().regex(/^[+0-9 ()-]{7,20}$/), institution: z.string().trim().min(2).max(160), course: z.string().trim().min(2).max(120), yearSemester: z.string().trim().min(1).max(40), city: z.string().trim().min(2).max(80).optional().default(''), age: z.coerce.number().int().min(3).max(120).optional() });
async function ownedRegistration(competitionId, userId) { return Registration.findOne({ competition: competitionId, user: userId }); }
async function organizer(userId) { const user = await User.findById(userId).select('role').lean(); return user && ['admin', 'organizer'].includes(user.role); }
async function editable(competitionId, userId) { const [competition, registration] = await Promise.all([Competition.findById(competitionId), ownedRegistration(competitionId, userId)]); if (!competition) throw Object.assign(new Error('Competition not found.'), { status: 404 }); if (!registration) throw Object.assign(new Error('Register before managing participants.'), { status: 403 }); if (new Date() >= competition.submissionStartsAt) throw Object.assign(new Error('Participants can no longer be changed.'), { status: 422 }); return { competition, registration }; }
export async function myParticipants(req, res) { const registration = await ownedRegistration(req.params.id, req.user.sub); if (!registration) return res.status(403).json({ error: 'Register before managing participants.' }); res.json(await Participant.find({ registration: registration._id }).sort({ role: 1, createdAt: 1 }).lean()); }
export async function addParticipant(req, res, next) { try { const { competition, registration } = await editable(req.params.id, req.user.sub); if (await Participant.countDocuments({ registration: registration._id }) >= competition.maxParticipantsPerRegistration) return res.status(422).json({ error: 'Participant limit reached.' }); const participant = await Participant.create({ ...participantInput.parse(req.body), registration: registration._id, role: 'participant' }); res.status(201).json(participant); } catch (error) { if (error.status) return res.status(error.status).json({ error: error.message }); next(error); } }
export async function updateParticipant(req, res, next) { try { const { registration } = await editable(req.params.id, req.user.sub); const participant = await Participant.findOneAndUpdate({ _id: req.params.participantId, registration: registration._id, role: 'participant' }, participantInput.partial().parse(req.body), { new: true, runValidators: true }); if (!participant) return res.status(404).json({ error: 'Participant not found or primary participant cannot be edited here.' }); res.json(participant); } catch (error) { if (error.status) return res.status(error.status).json({ error: error.message }); next(error); } }
export async function deleteParticipant(req, res, next) { try { const { registration } = await editable(req.params.id, req.user.sub); const participant = await Participant.findOneAndDelete({ _id: req.params.participantId, registration: registration._id, role: 'participant' }); if (!participant) return res.status(404).json({ error: 'Participant not found or primary participant cannot be removed.' }); res.status(204).end(); } catch (error) { if (error.status) return res.status(error.status).json({ error: error.message }); next(error); } }
export async function allParticipants(req, res) { if (!(await organizer(req.user.sub))) return res.status(403).json({ error: 'Organizer access is required.' }); const page = Math.max(1, Number(req.query.page) || 1), limit = Math.min(100, Math.max(1, Number(req.query.limit) || 20)), q = String(req.query.search || '').trim(); const filter = { ...(q ? { $or: [{ name: new RegExp(q, 'i') }, { email: new RegExp(q, 'i') }, { phone: new RegExp(q, 'i') }] } : {}) }; const registrations = await Registration.find({ competition: req.params.id }).select('_id').lean(); filter.registration = { $in: registrations.map((row) => row._id) }; const [rows, total] = await Promise.all([Participant.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), Participant.countDocuments(filter)]); const ids = [...new Set(rows.map((row) => row.registration.toString()))]; const detail = await Registration.find({ _id: { $in: ids } }).select('teamName status paymentStatus referralCode createdAt competition').lean(); const byId = new Map(detail.map((row) => [row._id.toString(), row])); res.json({ rows: rows.map((row) => ({ ...row, registration: byId.get(row.registration.toString()) })), page, limit, total, pages: Math.ceil(total / limit) }); }
export async function participantDetails(req, res) { if (!(await organizer(req.user.sub))) return res.status(403).json({ error: 'Organizer access is required.' }); const participant = await Participant.findById(req.params.participantId).lean(); if (!participant) return res.status(404).json({ error: 'Participant not found.' }); const registration = await Registration.findOne({ _id: participant.registration, competition: req.params.id }).lean(); if (!registration) return res.status(404).json({ error: 'Participant not found.' }); const teamMembers = await Participant.find({ registration: registration._id }).lean(); const referral = registration.referralCode ? await Referral.findOne({ referredUser: registration.user }).populate('referrerUser', 'name').lean() : null; res.json({ participant, registration, teamMembers, referral: referral ? { code: referral.referralCode, status: referral.status, referrer: referral.referrerUser?.name } : null }); }
export async function listSubmissions(req, res) { res.json(await Submission.find({ competition: req.params.id, user: req.user.sub }).lean()); }
export async function uploadSubmission(req, res) { const [competition, registration] = await Promise.all([Competition.findById(req.params.id), ownedRegistration(req.params.id, req.user.sub)]); if (!competition) return res.status(404).json({ error: 'Competition not found.' }); if (!registration) return res.status(403).json({ error: 'Register before submitting.' }); const now = new Date(); if (now < competition.submissionStartsAt || now >= competition.submissionEndsAt) return res.status(422).json({ error: 'Submissions are not open.' }); if (!req.file) return res.status(400).json({ error: 'Choose a video file.' }); const submission = await Submission.findOneAndUpdate({ competition: competition._id, user: req.user.sub }, { fileName: req.file.originalname, fileType: req.file.mimetype, fileSize: req.file.size, filePath: `/uploads/submissions/${req.file.filename}`, status: 'submitted' }, { new: true, upsert: true, setDefaultsOnInsert: true }); registration.status = 'submitted'; await registration.save(); res.status(201).json(submission); }
export async function deleteSubmission(req, res) { const competition = await Competition.findById(req.params.id); if (!competition || new Date() >= competition.submissionEndsAt) return res.status(422).json({ error: 'Submission cannot be deleted now.' }); const submission = await Submission.findOneAndDelete({ _id: req.params.submissionId, competition: req.params.id, user: req.user.sub }); if (!submission) return res.status(404).json({ error: 'Submission not found.' }); res.status(204).end(); }
export async function myReferral(req, res) { const user = await User.findById(req.user.sub).select('referralCode referralPoints'); const uses = await Referral.countDocuments({ referrerUser: req.user.sub }); const competitionId = String(req.query.competitionId || ''); const link = config.publicAppUrl && competitionId ? `${config.publicAppUrl.replace(/\/$/, '')}/competitions/${encodeURIComponent(competitionId)}?ref=${encodeURIComponent(user.referralCode)}` : null; res.json({ code: user.referralCode, link, baseUrl: config.publicAppUrl, points: user.referralPoints, uses, rewardPerSignup: 10 }); }
export async function trackReferral(req, res) { const code = z.object({ referralCode: z.string().min(3) }).parse(req.body).referralCode.toUpperCase(); const referrer = await User.findOne({ referralCode: code }); if (!referrer) return res.status(404).json({ error: 'Referral code not found.' }); if (referrer.id === req.user.sub) return res.status(422).json({ error: 'You cannot use your own referral.' }); if (await Referral.exists({ referredUser: req.user.sub })) return res.status(409).json({ error: 'A referral is already attributed to you.' }); await Referral.create({ referralCode: code, referrerUser: referrer._id, referredUser: req.user.sub }); referrer.referralPoints += 10; await referrer.save(); res.status(201).json({ message: 'Referral attributed.' }); }
export async function listReviews(req, res) { res.json(await Review.find({ competition: req.params.id }).populate('user', 'name avatarUrl').sort({ createdAt: -1 }).lean()); }
export async function addReview(req, res) { const registered = await ownedRegistration(req.params.id, req.user.sub); if (!registered) return res.status(403).json({ error: 'Only participants can add a review.' }); const body = z.object({ rating: z.coerce.number().int().min(1).max(5), text: z.string().min(3).max(500) }).parse(req.body); const review = await Review.findOneAndUpdate({ competition: req.params.id, user: req.user.sub }, body, { new: true, upsert: true, setDefaultsOnInsert: true }); res.status(201).json(review); }
