import React,{useCallback,useEffect,useState}from'react';
import {ActivityIndicator,FlatList,RefreshControl,StyleSheet,Text,TextInput,View}from'react-native';
import {competitions,home,me,referral}from'../api/extended';
import {CompetitionCard}from'../components/CompetitionCard';
import {Card,colors,PrimaryButton}from'../components/ui';
export function Catalog({onDetails,t,mode='explore'}){const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[status,setStatus]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{setRows(await competitions({q,lifecycle:status||undefined,sort:'closing'}))}catch(e){setError(e.response?.status===401?'Please log in to explore competitions.':(e.response?.data?.error||'Unable to load competitions.'))}finally{setLoading(false)}},[q,status]);useEffect(()=>{const x=setTimeout(load,250);return()=>clearTimeout(x)},[load]);const header=<><Text style={styles.heading}>{mode==='explore'?t.explore:t.competitions}</Text>{mode==='explore'&&<TextInput value={q} onChangeText={setQ} placeholder="Search by title or category" style={styles.search}/>}<View style={styles.filters}>{['','registration_open','upcoming','completed'].map(x=><Text key={x||'all'} onPress={()=>setStatus(x)} style={[styles.filter,status===x&&styles.selected]}>{x?x.replace('_',' '):'All'}</Text>)}</View></>;if(loading&&!rows.length)return <View style={styles.center}><ActivityIndicator color={colors.teal}/><Text>{t.loading}</Text></View>;if(error)return <View style={styles.center}><Text>{error}</Text><PrimaryButton onPress={load}>{t.retry}</PrimaryButton></View>;return <FlatList data={rows} keyExtractor={x=>x._id} ListHeaderComponent={header} renderItem={({item})=><CompetitionCard item={item} onPress={()=>onDetails(item._id)}/>} ListEmptyComponent={<Text style={styles.empty}>{t.empty}</Text>} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>}/>}
export function Home({onDetails,t}){const[data,setData]=useState(null),[error,setError]=useState('');const load=async()=>{try{setData(await home())}catch(e){setError(e.response?.data?.error||'Unable to load home.')}};useEffect(()=>{load()},[]);if(error)return <View style={styles.center}><Text>{error}</Text><PrimaryButton onPress={load}>{t.retry}</PrimaryButton></View>;if(!data)return <View style={styles.center}><ActivityIndicator color={colors.teal}/></View>;return <FlatList data={data.upcoming} keyExtractor={x=>x._id} ListHeaderComponent={<><Text style={styles.heading}>Welcome back</Text><Text style={styles.sub}>Featured competition</Text>{data.featured&&<CompetitionCard item={data.featured} onPress={()=>onDetails(data.featured._id)}/>}<Text style={styles.sub}>Upcoming competitions</Text></>} renderItem={({item})=><CompetitionCard item={item} onPress={()=>onDetails(item._id)}/>}/>}
export function Profile({t,onLogout}){const[user,setUser]=useState(null),[ref,setRef]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=async()=>{setLoading(true);setError('');try{const[a,b]=await Promise.all([me(),referral()]);setUser(a);setRef(b)}catch(e){setError(e.response?.status===401?'Your session has expired. Please log in again.':(e.response?.data?.error||'Unable to load your profile.'))}finally{setLoading(false)}};useEffect(()=>{load()},[]);if(loading)return <View style={styles.center}><ActivityIndicator color={colors.teal}/><Text>Loading profile…</Text></View>;if(error)return <View style={styles.center}><Text>{error}</Text><PrimaryButton onPress={load}>Retry</PrimaryButton><PrimaryButton onPress={onLogout}>Log in again</PrimaryButton></View>;return <View style={styles.profile}><Text style={styles.heading}>{t.profile}</Text><Card><Text style={styles.name}>{user.name}</Text><Text>{user.email}</Text><Text style={styles.sub}>{user.stats.joined} joined · {user.stats.submissions} submissions</Text></Card><Card><Text style={styles.name}>{t.refer}</Text><Text>{ref?.points||0} referral points</Text></Card><PrimaryButton onPress={onLogout}>Logout</PrimaryButton></View>}
const styles=StyleSheet.create({heading:{fontSize:26,fontWeight:'800',color:colors.ink,margin:16},sub:{fontWeight:'800',color:colors.ink,marginHorizontal:16,marginBottom:8},search:{margin:16,marginTop:0,borderWidth:1,borderColor:'#dbe1ec',borderRadius:10,padding:12},filters:{flexDirection:'row',flexWrap:'wrap',gap:8,marginHorizontal:16,marginBottom:8},filter:{padding:8,color:colors.muted,textTransform:'capitalize'},selected:{backgroundColor:colors.pale,color:colors.teal,fontWeight:'800',borderRadius:8},center:{flex:1,alignItems:'center',justifyContent:'center',gap:14,padding:24},empty:{textAlign:'center',color:colors.muted,margin:30},profile:{padding:16,gap:10},name:{fontSize:18,fontWeight:'800',color:colors.ink,marginBottom:5}});
