import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import multer from 'multer';
import path from 'node:path';
import fs from 'node:fs';
import { config } from './config.js';
import { register, login } from './controllers/authController.js';
import { details, featured, list, home, createRegistration, myRegistration, registrations } from './controllers/competitionController.js';
import { me, updateMe, avatar } from './controllers/userController.js';
import { myParticipants, allParticipants, participantDetails, addParticipant, updateParticipant, deleteParticipant, listSubmissions, uploadSubmission, deleteSubmission, myReferral, trackReferral, listReviews, addReview } from './controllers/extraController.js';
import { requireAuth } from './middleware/auth.js';
import { errorHandler, notFound } from './middleware/errors.js';

export const app = express();
app.use(cors({ origin: config.clientOrigin }));
app.use(helmet({ crossOriginResourcePolicy: false }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 250, standardHeaders: 'draft-7' }));
app.use(express.json({ limit: '32kb' }));
const uploadRoot = path.resolve('uploads'); fs.mkdirSync(path.join(uploadRoot, 'submissions'), { recursive: true }); fs.mkdirSync(path.join(uploadRoot, 'avatars'), { recursive: true });
const storage = multer.diskStorage({ destination: (req, file, cb) => cb(null, file.fieldname === 'avatar' ? path.join(uploadRoot, 'avatars') : path.join(uploadRoot, 'submissions')), filename: (req, file, cb) => cb(null, `${Date.now()}-${crypto.randomUUID()}${path.extname(file.originalname).toLowerCase()}`) });
const upload = multer({ storage, limits: { fileSize: 100 * 1024 * 1024 }, fileFilter: (req, file, cb) => cb(null, file.fieldname === 'avatar' ? /^image\/(jpeg|png|webp)$/.test(file.mimetype) : /^video\/(mp4|quicktime|webm)$/.test(file.mimetype)) });
app.use('/uploads', express.static(uploadRoot));
app.get('/health', (req, res) => res.json({ ok: true }));
app.post('/api/auth/register', register);
app.post('/api/auth/login', login);
app.get('/api/home', requireAuth, home);
app.get('/api/competitions/featured', requireAuth, featured);
app.get('/api/competitions', requireAuth, list);
app.get('/api/competitions/:id', requireAuth, details);
app.post('/api/competitions/:id/registrations', requireAuth, createRegistration);
app.get('/api/competitions/:id/registrations/me', requireAuth, myRegistration);
app.get('/api/competitions/:id/registrations', requireAuth, registrations);
app.get('/api/competitions/:id/participants/me', requireAuth, myParticipants); app.get('/api/competitions/:id/participants', requireAuth, allParticipants); app.get('/api/competitions/:id/participants/:participantId', requireAuth, participantDetails); app.post('/api/competitions/:id/participants', requireAuth, addParticipant); app.patch('/api/competitions/:id/participants/:participantId', requireAuth, updateParticipant); app.delete('/api/competitions/:id/participants/:participantId', requireAuth, deleteParticipant);
app.get('/api/competitions/:id/submissions', requireAuth, listSubmissions); app.post('/api/competitions/:id/submissions', requireAuth, upload.single('submission'), uploadSubmission); app.delete('/api/competitions/:id/submissions/:submissionId', requireAuth, deleteSubmission);
app.get('/api/competitions/:id/reviews', requireAuth, listReviews); app.post('/api/competitions/:id/reviews', requireAuth, addReview);
app.get('/api/users/me', requireAuth, me); app.patch('/api/users/me', requireAuth, updateMe); app.post('/api/users/me/avatar', requireAuth, upload.single('avatar'), avatar);
app.get('/api/referrals/me', requireAuth, myReferral); app.post('/api/referrals/track', requireAuth, trackReferral);
app.use(notFound);
app.use(errorHandler);
